export const ROLES = {
  ADMIN: "ROLE_ADMIN",
  STORE_ADMIN: "ROLE_STORE_ADMIN",
  STORE_MANAGER: "ROLE_STORE_MANAGER",
  BRANCH_MANAGER: "ROLE_BRANCH_MANAGER",
  BRANCH_CASHIER: "ROLE_BRANCH_CASHIER",
};