import { ROLES } from "@/constants/roles";

export const PERMISSIONS = {
  CUSTOMER_VIEW: "CUSTOMER_VIEW",
  CUSTOMER_CREATE: "CUSTOMER_CREATE",
  CUSTOMER_UPDATE: "CUSTOMER_UPDATE",
  CUSTOMER_DELETE: "CUSTOMER_DELETE",

  SHIFT_VIEW: "SHIFT_VIEW",
  SHIFT_START: "SHIFT_START",
  SHIFT_END: "SHIFT_END",
};

export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_UPDATE,
    PERMISSIONS.CUSTOMER_DELETE,

    PERMISSIONS.SHIFT_VIEW,
  ],

  [ROLES.STORE_ADMIN]: [
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_UPDATE,

    PERMISSIONS.SHIFT_VIEW,
  ],

  [ROLES.STORE_MANAGER]: [
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_UPDATE,

    PERMISSIONS.SHIFT_VIEW,
  ],

  [ROLES.BRANCH_MANAGER]: [
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_UPDATE,

    PERMISSIONS.SHIFT_VIEW,
  ],

  [ROLES.BRANCH_CASHIER]: [
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_UPDATE,

    PERMISSIONS.SHIFT_VIEW,
    PERMISSIONS.SHIFT_START,
    PERMISSIONS.SHIFT_END,
  ],
};