import {
  ResponsiveContainer,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
} from "recharts";

import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

const formatCurrency = (value) =>
  `₹${Number(value || 0).toLocaleString("en-IN")}`;

const CategorySalesChart = ({ data = [] }) => {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Category Sales</CardTitle>

        <p className="text-sm text-muted-foreground">
          Sales generated by category.
        </p>
      </CardHeader>

      <CardContent>
        {data.length === 0 ? (
          <div className="flex h-[300px] items-center justify-center text-sm text-muted-foreground">
            No category sales data available.
          </div>
        ) : (
          <div className="h-[300px] w-full">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart
                data={data}
                margin={{
                  top: 10,
                  right: 10,
                  left: 10,
                  bottom: 5,
                }}
              >
                <CartesianGrid strokeDasharray="3 3" />

                <XAxis
                  dataKey="categoryName"
                  tick={{ fontSize: 11 }}
                  interval={0}
                  angle={-25}
                  textAnchor="end"
                  height={60}
                />

                <YAxis
                  tick={{ fontSize: 12 }}
                  tickFormatter={formatCurrency}
                />

                <Tooltip
                  formatter={(value) => [
                    formatCurrency(value),
                    "Sales",
                  ]}
                />

                <Bar
                  dataKey="totalSales"
                  fill="currentColor"
                  className="text-primary"
                  radius={[4, 4, 0, 0]}
                />
              </BarChart>
            </ResponsiveContainer>
          </div>
        )}
      </CardContent>
    </Card>
  );
};

export default CategorySalesChart;